version: 0.2

phases:
pre_build:
commands:
- echo Logging in to Amazon ECR...
- aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

build:
commands:
- echo Building Docker image...
- docker build -t product-node-app .

post_build:
commands:
- echo Tagging Docker image...
- docker tag product-node-app:latest $REPOSITORY_URI:latest
- echo Pushing Docker image to ECR...
- docker push $REPOSITORY_URI:latest
- echo Build completed successfully

artifacts:
files:
- '**/*'
