version: 0.2

env:
  variables:
    REPOSITORY_URI: <your-ecr-uri>

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - docker build -t product-node-app .
      - docker tag product-node-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
