echo Logging into Amazon ECR...

aws ecr get-login-password --region ap-south-1 \
| docker login --username AWS --password-stdin 500766169087.dkr.ecr.ap-south-1.amazonaws.com

echo Build Docker image
docker build -t product-node-app .

echo Tag image
docker tag product-node-app:latest $REPOSITORY_URI:latest

echo Push image
docker push $REPOSITORY_URI:latest
